"use client"
import { useState } from "react"
import Link from "next/link"
import { useParams } from "next/navigation"
import { ArrowLeft, Building2, CheckCircle2, Globe, MapPin, Users } from "lucide-react"
import { SiteHeader } from "@/components/site-header"
import { SiteFooter } from "@/components/site-footer"

export default function CompanyDetail() {
  const {slug}=useParams<{slug:string}>()
  const [followed,setFollowed]=useState(false)
  const name=slug.split("-").map(x=>x[0].toUpperCase()+x.slice(1)).join(" ")
  return <main className="route-home min-h-screen bg-[#f6f8f7]"><SiteHeader/><div className="mx-auto max-w-[1120px] px-4 py-5 text-sm text-slate-500"><Link href="/companies" className="inline-flex items-center gap-1 hover:text-[#008f40]"><ArrowLeft className="size-4"/>Danh sách công ty</Link></div>
    <section className="bg-[linear-gradient(110deg,#063c27,#087b43,#00b14f)]"><div className="mx-auto max-w-[1120px] px-4 py-12 sm:px-6"><div className="flex flex-col gap-5 sm:flex-row sm:items-end"><span className="grid size-24 place-items-center rounded-2xl border-4 border-white bg-white text-2xl font-black text-[#087b43] shadow-xl">{name.split(" ").map(x=>x[0]).slice(0,2).join("")}</span><div className="flex-1 text-white"><span className="rounded-full bg-amber-300 px-2.5 py-1 text-xs font-bold text-amber-950">Pro Company</span><h1 className="mt-3 text-3xl font-extrabold">{name}</h1><p className="mt-2 flex items-center gap-2 text-sm text-emerald-50"><Globe className="size-4"/>{slug}.topcv.vn <span>·</span><Users className="size-4"/>500+ nhân sự</p></div><button onClick={()=>setFollowed(value=>!value)} className={`rounded-xl px-5 py-3 text-sm font-bold ${followed?"bg-emerald-100 text-[#087b43]":"bg-white text-[#087b43]"}`}>{followed?"✓ Đang theo dõi":"+ Theo dõi công ty"}</button></div></div></section>
    <section className="mx-auto grid max-w-[1120px] gap-6 px-4 py-8 sm:px-6 lg:grid-cols-[1.5fr_.8fr]"><article className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Giới thiệu công ty</h2><p className="mt-4 text-sm leading-7 text-slate-600">{name} xây dựng những sản phẩm và dịch vụ có tác động tích cực, đặt con người và sự đổi mới làm trung tâm. Đội ngũ cùng học hỏi, làm việc minh bạch và tạo ra giá trị dài hạn cho khách hàng.</p><h3 className="mt-7 font-bold">Vì sao nên gia nhập?</h3><div className="mt-4 space-y-3">{["Lộ trình phát triển minh bạch cùng mentor đồng hành","Môi trường linh hoạt, đề cao hiệu quả và tinh thần sở hữu","Phúc lợi toàn diện, hoạt động gắn kết đội ngũ"].map(x=><p key={x} className="flex gap-2 text-sm text-slate-600"><CheckCircle2 className="size-5 shrink-0 text-[#00b14f]"/>{x}</p>)}</div></article><aside className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Thông tin chung</h2><div className="mt-5 space-y-5 text-sm"><p className="flex gap-3"><Building2 className="size-5 text-[#00a64f]"/><span><b className="block">Lĩnh vực</b><span className="text-slate-500">Công nghệ · Dịch vụ số</span></span></p><p className="flex gap-3"><Users className="size-5 text-[#00a64f]"/><span><b className="block">Quy mô</b><span className="text-slate-500">500 - 1.000 nhân viên</span></span></p><p className="flex gap-3"><MapPin className="size-5 text-[#00a64f]"/><span><b className="block">Địa điểm</b><span className="text-slate-500">Hà Nội · Hồ Chí Minh</span></span></p></div><Link href="/discover/jobs-by-field" className="mt-7 block w-full rounded-xl bg-[#00b14f] py-3 text-center text-sm font-bold text-white">Xem 18 vị trí đang tuyển</Link></aside></section><SiteFooter/>
  </main>
}
