import Link from "next/link"
import Image from "next/image"
import { ArrowRight, BookOpen, BriefcaseBusiness, Clock3, Lightbulb, TrendingUp } from "lucide-react"
import { SiteHeader } from "@/components/site-header"
import { SiteFooter } from "@/components/site-footer"
import { careerArticles } from "@/lib/career-articles"

const categories = [
  { id: "orientation", title: "Định hướng nghề nghiệp", desc: "Chọn lộ trình phù hợp với thế mạnh và mục tiêu dài hạn.", icon: Lightbulb },
  { id: "job-search", title: "Bí kíp tìm việc", desc: "Từ CV, phỏng vấn đến cách theo dõi kết quả ứng tuyển.", icon: BriefcaseBusiness },
  { id: "salary", title: "Lương & phúc lợi", desc: "Hiểu thu nhập, phúc lợi và đàm phán offer tự tin hơn.", icon: TrendingUp },
  { id: "skills", title: "Kỹ năng chuyên môn", desc: "Kiến thức thực chiến để làm việc hiệu quả và thăng tiến.", icon: BookOpen },
]
export default function CareerGuide(){return <main className="route-home min-h-screen bg-[#f6f8f7]"><SiteHeader/><section className="relative overflow-hidden bg-gradient-to-r from-[#06452f] via-[#087b43] to-[#00a64f] py-12 text-white sm:py-16"><div className="absolute -left-20 top-0 size-72 rounded-full bg-emerald-300/10 blur-3xl"/><div className="relative mx-auto grid max-w-[1120px] items-center gap-8 px-4 sm:px-6 lg:grid-cols-[1fr_.9fr]"><div><p className="text-sm font-semibold text-emerald-100">Cẩm nang nghề nghiệp</p><h1 className="mt-2 max-w-2xl text-3xl font-bold leading-tight sm:text-4xl">Kiến thức đúng lúc cho hành trình sự nghiệp của bạn</h1><p className="mt-4 max-w-2xl leading-7 text-emerald-50/90">Hướng dẫn ngắn gọn, thực tế và có thể áp dụng ngay khi tìm việc, phát triển kỹ năng hoặc chuẩn bị cho bước tiến tiếp theo.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="#featured" className="rounded-xl bg-white px-4 py-2.5 text-sm font-bold text-[#087b43]">Đọc bài nổi bật</Link><Link href="/cv-builder" className="rounded-xl border border-white/30 px-4 py-2.5 text-sm font-bold">Tạo CV ngay</Link></div></div><div className="relative overflow-hidden rounded-[1.75rem] border border-white/20 bg-white shadow-2xl"><Image src="/images/topcv-career-guide.png" alt="Ứng viên cùng xây dựng lộ trình phát triển nghề nghiệp" width={1536} height={1024} className="h-auto w-full"/></div></div></section>
<div className="mx-auto max-w-[1120px] px-4 py-9 sm:px-6"><section><div className="mb-5"><p className="text-sm font-bold text-[#008f40]">KHÁM PHÁ THEO CHỦ ĐỀ</p><h2 className="mt-1 text-2xl font-bold">Bạn đang cần hỗ trợ điều gì?</h2></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{categories.map(({id,title,desc,icon:Icon})=><a href={`#${id}`} key={id} className="group rounded-2xl bg-white p-5 shadow-sm transition hover:-translate-y-1 hover:shadow-md"><span className="grid size-11 place-items-center rounded-xl bg-[#e7f9ef] text-[#008f40]"><Icon className="size-5"/></span><h3 className="mt-4 font-bold group-hover:text-[#008f40]">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{desc}</p><span className="mt-4 inline-flex items-center gap-1 text-sm font-bold text-[#008f40]">Xem nội dung <ArrowRight className="size-4"/></span></a>)}</div></section>
<section id="featured" className="mt-10"><div className="mb-5"><p className="text-sm font-bold text-[#008f40]">BÀI VIẾT NỔI BẬT</p><h2 className="mt-1 text-2xl font-bold">Nội dung có thể áp dụng ngay</h2></div><div className="grid gap-5 md:grid-cols-2">{careerArticles.map((article,index)=><Link href={`/career-guide/${article.slug}`} id={index===0?"job-search":index===1?"salary":index===2?"orientation":"skills"} key={article.slug} className="group overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className={`h-2 ${index===0?"bg-[#087b43]":index===1?"bg-[#203246]":index===2?"bg-[#b46b08]":"bg-[#2563eb]"}`}/><article className="p-6"><div className="flex items-center justify-between gap-3"><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">{article.category}</span><span className="flex items-center gap-1.5 text-xs text-slate-400"><Clock3 className="size-3.5"/>{article.readTime} đọc</span></div><h3 className="mt-5 text-xl font-bold leading-snug text-slate-900 group-hover:text-[#008f40]">{article.title}</h3><p className="mt-3 line-clamp-3 text-sm leading-6 text-slate-600">{article.excerpt}</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-bold text-[#008f40]">Đọc bài viết <ArrowRight className="size-4 transition-transform group-hover:translate-x-1"/></span></article></Link>)}</div></section>
<section className="mt-10 rounded-2xl bg-[#e7f9ef] p-6 sm:p-8"><div className="grid gap-6 md:grid-cols-[1fr_auto] md:items-center"><div><p className="text-sm font-bold text-[#008f40]">KỸ NĂNG CHUYÊN MÔN</p><h2 className="mt-2 text-2xl font-bold">Biến kiến thức thành bằng chứng năng lực</h2><p className="mt-3 max-w-2xl leading-7 text-slate-600">Chọn một kỹ năng sát với công việc mục tiêu, tạo dự án thực hành và đưa kết quả cụ thể vào CV.</p></div><Link href="/career-guide/xay-dung-bang-chung-nang-luc" className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#00b14f] px-5 py-3 text-sm font-bold text-white">Đọc hướng dẫn <ArrowRight className="size-4"/></Link></div></section>
<section id="help" className="mt-10 grid gap-4 md:grid-cols-3"><Info id="about" title="Về TopCV" text="Nền tảng kết nối ứng viên, doanh nghiệp và các công cụ phát triển sự nghiệp."/><Info id="privacy" title="Bảo mật thông tin" text="Hồ sơ chỉ được chia sẻ theo cài đặt của bạn và phạm vi cần thiết cho tuyển dụng."/><Info id="terms" title="Nguyên tắc sử dụng" text="Thông tin tuyển dụng cần trung thực; người dùng chịu trách nhiệm về nội dung đăng tải."/></section></div><SiteFooter/></main>}

function Info({id,title,text}:{id:string;title:string;text:string}){return <article id={id} className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="font-bold">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></article>}
