"use client";
import { Children, isValidElement, useState, type ReactNode } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { httpRequest } from "@/lib/utils";
import { useAccountStore } from "@/stores/auth.store";
import { conversationService } from "@/services/conversation.service";

import Link from "next/link";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
const labels: Record<string, string> = { submitted: "Mới ứng tuyển", reviewing: "Đang xem xét", interview: "Phỏng vấn", hired: "Đã tuyển", rejected: "Từ chối" };
type Profile = { id: string; fullName: string; headline: string | null; careerGoal: string | null; experienceYears: string | null; currentLocation: { name: string } | null };
type Application = { id: string; status: string; fitScore: string | null; internalNote: string | null; coverLetter: string | null; appliedAt: string; candidate: Profile; jobPost: { id: string; title: string }; cv: { id: string; title: string; deletedAt: string | null } | null };
type Page<T> = { items: T[]; total: number; page: number; pages: number };
type Summary = { days: number; jobs: number; activeJobs: number; total: number; statuses: { status: string; count: number }[]; recent: { id: string; candidate: { fullName: string }; jobPost: { title: string }; status: string; appliedAt: string }[]; reports: { id: string; title: string; counts: Record<string, number> }[] };
const inputClass = "min-w-0 rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm";
const buttonClass = "rounded-xl bg-emerald-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50";
async function get<T>(path: string, params?: object, signal?: AbortSignal): Promise<T> { return (await httpRequest.get(`/employer/${path}`, { params, signal })).data.data; }
function Panel({ title, children }: { title: string; children: ReactNode }) { return <section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="mb-5 text-xl font-semibold">{title}</h2>{children}</section>; }
function Pager({ page, pages, change }: { page: number; pages: number; change: (p: number) => void }) { return <div className="mt-5 flex items-center justify-end gap-4 text-sm"><button disabled={page <= 1} onClick={() => change(page - 1)} className="disabled:opacity-40">Trước</button><span>Trang {page}/{Math.max(1, pages)}</span><button disabled={page >= pages} onClick={() => change(page + 1)} className="disabled:opacity-40">Sau</button></div>; }
function ErrorRetry({ retry }: { retry: () => void }) { return <button className="text-sm text-red-600" onClick={retry}>Không tải được dữ liệu. Thử lại</button>; }

export function EmployerSummary({ report = false, open }: { report?: boolean; open?: (tab: string) => void }) {
  const account = useAccountStore(s => s.account);
  const [days, setDays] = useState(30);
  const query = useQuery({ queryKey: ["employer", account?.id, "summary", days], enabled: account?.role === "company", queryFn: ({ signal }) => get<Summary>("summary", { days }, signal) });
  const data = query.data;
  return <Panel title={report ? "Báo cáo tuyển dụng" : "Tổng quan tuyển dụng"}>
    <div className="mb-5 flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-slate-500">Hồ sơ ứng tuyển trong {days} ngày gần nhất</p><EmployerDropdown aria-label="Khoảng thời gian báo cáo" className={inputClass} value={days} onChange={e => setDays(Number(e.target.value))}>{[7,30,90,365].map(n => <option key={n} value={n}>{n} ngày</option>)}</EmployerDropdown></div>
    {query.isPending && <p>Đang tải...</p>}{query.isError && <ErrorRetry retry={() => void query.refetch()}/>}
    {data && <><div className="grid grid-cols-2 gap-3 xl:grid-cols-4">{[["Tổng tin hiện có",data.jobs],["Tin đang tuyển",data.activeJobs],["Lượt ứng tuyển",data.total],["Đã tuyển",data.statuses.find(s=>s.status==="hired")?.count??0]].map(([label,value])=><div key={label} className="rounded-xl border bg-emerald-50/50 p-4"><p className="text-sm text-slate-600">{label}</p><p className="mt-2 text-3xl font-bold text-emerald-800">{value}</p></div>)}</div>
      <div className="my-6 space-y-3">{Object.entries(labels).map(([status,label])=>{const count=data.statuses.find(s=>s.status===status)?.count??0;return <div key={status}><div className="flex justify-between text-sm"><span>{label}</span><span>{count}</span></div><div className="mt-1 h-2 rounded bg-slate-100"><div className="h-2 rounded bg-emerald-500" style={{width:`${data.total?count/data.total*100:0}%`}}/></div></div>;})}</div>
      {report ? <><p className="mb-3 text-xs text-slate-500">Trạng thái hiện tại của các hồ sơ nhận trong kỳ; không phải lịch sử chuyển trạng thái.</p><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th className="p-2">Tin tuyển dụng</th>{Object.entries(labels).map(([k,v])=><th className="p-2" key={k}>{v}</th>)}</tr></thead><tbody>{data.reports.map(row=><tr className="border-t" key={row.id}><td className="p-2">{row.title}</td>{Object.keys(labels).map(k=><td className="p-2" key={k}>{row.counts[k]??0}</td>)}</tr>)}</tbody></table>{!data.reports.length&&<p className="py-6 text-slate-500">Chưa có tin tuyển dụng.</p>}</div></> : <><div className="mb-3 flex justify-between"><h3 className="font-semibold">Ứng tuyển gần đây</h3><button className="text-sm text-emerald-700" onClick={()=>open?.("candidates")}>Xem tất cả</button></div>{!data.recent.length&&<p className="text-sm text-slate-500">Chưa có ứng tuyển trong khoảng thời gian này.</p>}{data.recent.map(a=><div className="flex flex-wrap justify-between gap-2 border-t py-3 text-sm" key={a.id}><div><b>{a.candidate.fullName}</b><p className="text-slate-500">{a.jobPost.title}</p></div><span>{labels[a.status]} · {new Date(a.appliedAt).toLocaleDateString("vi-VN")}</span></div>)}</>}
    </>}
  </Panel>;
}

function MessageButton({ id }: { id: string }) {
  const router=useRouter();
  const mutation=useMutation({mutationFn:()=>conversationService.create(id),onSuccess:c=>router.push(`/employer/messages?conversation=${encodeURIComponent(c.id)}`),onError:()=>toast.error("Không thể mở cuộc trò chuyện.")});
  return <button disabled={mutation.isPending} onClick={()=>mutation.mutate()} className={buttonClass}>{mutation.isPending?"Đang mở...":"Nhắn tin"}</button>;
}
export function EmployerApplications() {
  const account=useAccountStore(s=>s.account);
  const [page,setPage]=useState(1),[search,setSearch]=useState(""),[query,setQuery]=useState(""),[status,setStatus]=useState(""),[job,setJob]=useState("");
  const [selected,setSelected]=useState<Application|null>(null);
  const jobs=useQuery({queryKey:["employer",account?.id,"jobs"],enabled:account?.role==="company",queryFn:({signal})=>get<{id:string;title:string}[]>("jobs",undefined,signal)});
  const list=useQuery({queryKey:["employer",account?.id,"applications",page,query,status,job],enabled:account?.role==="company",queryFn:({signal})=>get<Page<Application>>("applications",{page,query,...(status?{status}:{}),...(job?{jobPostId:job}:{})},signal)});
  return <Panel title="Ứng viên ứng tuyển · Mini ATS"><form className="mb-5 flex flex-wrap gap-2" onSubmit={e=>{e.preventDefault();setQuery(search);setPage(1);}}><input aria-label="Tìm ứng viên" className={inputClass} placeholder="Tên ứng viên" value={search} onChange={e=>setSearch(e.target.value)}/><EmployerDropdown aria-label="Lọc tin tuyển dụng" className={inputClass} value={job} onChange={e=>{setJob(e.target.value);setPage(1);}}><option value="">Tất cả tin</option>{jobs.data?.map(j=><option key={j.id} value={j.id}>{j.title}</option>)}</EmployerDropdown><EmployerDropdown aria-label="Lọc trạng thái" className={inputClass} value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">Tất cả trạng thái</option>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</EmployerDropdown><button className={buttonClass}>Tìm kiếm</button></form>
    {list.isPending&&<p>Đang tải...</p>}{list.isError&&<ErrorRetry retry={()=>void list.refetch()}/>}{list.data&&<><p className="mb-3 text-sm text-slate-500">{list.data.total} hồ sơ</p>{!list.data.items.length&&<p className="rounded-xl border border-dashed p-8 text-center text-slate-500">Không có hồ sơ phù hợp.</p>}{list.data.items.map(a=><div key={a.id} className="mb-3 flex flex-wrap items-center justify-between gap-3 rounded-xl border p-4"><div><h3 className="font-semibold">{a.candidate.fullName}</h3><p className="text-sm text-slate-500">{a.jobPost.title}</p><p className="mt-1 text-xs">{labels[a.status]} · {new Date(a.appliedAt).toLocaleDateString("vi-VN")} · Điểm: {a.fitScore??"Chưa đánh giá"}</p></div><button className={buttonClass} onClick={()=>setSelected(a)}>Xem hồ sơ</button></div>)}<Pager page={page} pages={list.data.pages} change={setPage}/></>}
    {selected&&<ApplicationEditor key={selected.id} item={selected} close={()=>setSelected(null)}/>}
  </Panel>;
}
function ApplicationEditor({item,close}:{item:Application;close:()=>void}) {
  const client=useQueryClient();const account=useAccountStore(s=>s.account);
  const [status,setStatus]=useState(item.status),[score,setScore]=useState(item.fitScore??""),[note,setNote]=useState(item.internalNote??"");
  const [showCv,setShowCv]=useState(false);
  const cv=useQuery({queryKey:["employer",account?.id,"cv",item.id],enabled:showCv,queryFn:()=>get<{title:string;url:string|null;content:unknown}>(`applications/${item.id}/cv`)});
  const save=useMutation({mutationFn:()=>httpRequest.patch(`/employer/applications/${item.id}`,{status,fitScore:score===""?null:Number(score),internalNote:note}),onSuccess:()=>{void client.invalidateQueries({queryKey:["employer",account?.id]});toast.success("Đã cập nhật hồ sơ ứng tuyển");close();},onError:()=>toast.error("Không thể lưu thay đổi. Vui lòng thử lại.")});
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" role="dialog" aria-modal="true" aria-label="Hồ sơ ứng tuyển"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6"><div className="flex justify-between gap-4"><h2 className="text-xl font-bold">{item.candidate.fullName}</h2><button onClick={close} aria-label="Đóng hồ sơ">✕</button></div><p className="mt-2 text-slate-500">{item.jobPost.title}</p><p className="my-3 text-sm">{item.candidate.headline} · {item.candidate.currentLocation?.name??"Chưa có địa điểm"} · {item.candidate.experienceYears??0} năm kinh nghiệm</p><p className="whitespace-pre-wrap text-sm">{item.coverLetter??"Không có thư ứng tuyển."}</p><div className="my-4 flex gap-3"><MessageButton id={item.candidate.id}/>{item.cv&&!item.cv.deletedAt&&<button className="text-sm text-emerald-700 underline" onClick={()=>setShowCv(!showCv)}>Xem CV: {item.cv.title}</button>}</div>
    {showCv&&<div className="mb-4 rounded-xl border p-3">{cv.isPending&&<p>Đang tải CV...</p>}{cv.isError&&<ErrorRetry retry={()=>void cv.refetch()}/>}{cv.data?.url&&<a href={cv.data.url} target="_blank" rel="noopener noreferrer" className="text-emerald-700 underline">Mở file CV</a>}{cv.data?.content!=null&&<CvContent value={cv.data.content}/>} {cv.data&&!cv.data.url&&!cv.data.content&&<p>CV chưa có nội dung.</p>}</div>}
    <form className="space-y-4 border-t pt-4" onSubmit={e=>{e.preventDefault();save.mutate();}}><label className="block text-sm">Trạng thái<EmployerDropdown className={`${inputClass} mt-1 w-full`} value={status} onChange={e=>setStatus(e.target.value)}>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</EmployerDropdown></label><label className="block text-sm">Điểm phù hợp (0–100, để trống nếu chưa đánh giá)<input type="number" min={0} max={100} step="0.01" className={`${inputClass} mt-1 w-full`} value={score} onChange={e=>setScore(e.target.value)}/></label><label className="block text-sm">Ghi chú nội bộ<textarea maxLength={10000} rows={4} className={`${inputClass} mt-1 w-full`} value={note} onChange={e=>setNote(e.target.value)}/></label><button disabled={save.isPending} className={buttonClass}>{save.isPending?"Đang lưu...":"Lưu thay đổi"}</button></form></div></div>;
}
const cvLabels:Record<string,string>={personal:"Thông tin cá nhân",fullName:"Họ tên",title:"Vị trí",email:"Email",phone:"Điện thoại",address:"Địa chỉ",objective:"Mục tiêu",experiences:"Kinh nghiệm",educations:"Học vấn",skills:"Kỹ năng",company:"Công ty",role:"Vị trí",timeline:"Thời gian",bullets:"Mô tả",school:"Trường",degree:"Bằng cấp",name:"Tên",level:"Mức độ"};
function CvContent({value}:{value:unknown}):ReactNode { if(value==null)return null; if(typeof value!=="object")return <span className="whitespace-pre-wrap break-words">{String(value)}</span>;return <div className="space-y-2">{Object.entries(value).filter(([k])=>!["id","avatar"].includes(k)).map(([k,v])=><div className="border-l pl-3 text-sm" key={k}>{!/^\d+$/.test(k)&&<b>{cvLabels[k]??k}: </b>}<CvContent value={v}/></div>)}</div>; }
export function EmployerTalent() {
  const account=useAccountStore(s=>s.account);const [page,setPage]=useState(1);
  const [draft,setDraft]=useState({query:"",location:"",experience:""}),[filters,setFilters]=useState(draft);
  const list=useQuery({queryKey:["employer",account?.id,"talent",page,filters],enabled:account?.role==="company",queryFn:({signal})=>get<Page<Profile>>("talent",{page,query:filters.query,location:filters.location,...(filters.experience!==""?{experience:filters.experience}:{})},signal)});
  return <Panel title="Tìm hồ sơ công khai"><p className="mb-4 text-sm text-slate-500">Các ứng viên cho phép nhà tuyển dụng tìm kiếm hồ sơ.</p><form className="mb-5 flex flex-wrap gap-2" onSubmit={e=>{e.preventDefault();setFilters({...draft});setPage(1);}}><input className={inputClass} aria-label="Tên hoặc chức danh" placeholder="Tên hoặc chức danh" value={draft.query} onChange={e=>setDraft({...draft,query:e.target.value})}/><input className={inputClass} aria-label="Tỉnh thành" placeholder="Tỉnh/thành phố" value={draft.location} onChange={e=>setDraft({...draft,location:e.target.value})}/><input className={inputClass} aria-label="Kinh nghiệm tối thiểu" placeholder="Số năm kinh nghiệm từ" type="number" min={0} max={99} value={draft.experience} onChange={e=>setDraft({...draft,experience:e.target.value})}/><button className={buttonClass}>Tìm kiếm</button></form>{list.isPending&&<p>Đang tải...</p>}{list.isError&&<ErrorRetry retry={()=>void list.refetch()}/>}{list.data&&<><p className="mb-3 text-sm text-slate-500">{list.data.total} hồ sơ phù hợp</p>{!list.data.items.length&&<p className="p-6 text-center text-slate-500">Không có hồ sơ phù hợp.</p>}<div className="grid gap-4 xl:grid-cols-2">{list.data.items.map(p=><article key={p.id} className="rounded-xl border p-4"><h3 className="font-semibold">{p.fullName}</h3><p className="text-emerald-700">{p.headline??"Chưa cập nhật chức danh"}</p><p className="my-2 text-sm text-slate-500">{p.currentLocation?.name??"Chưa có địa điểm"} · {p.experienceYears??0} năm kinh nghiệm</p><p className="mb-4 whitespace-pre-wrap text-sm">{p.careerGoal??"Chưa cập nhật mục tiêu nghề nghiệp."}</p><MessageButton id={p.id}/></article>)}</div><Pager page={page} pages={list.data.pages} change={setPage}/></>}</Panel>;
}

function EmployerDropdown({value,onChange,children,className,"aria-label":label}:{value:string|number;onChange:(e:{target:{value:string}})=>void;children:ReactNode;className?:string;"aria-label"?:string}) {
 const options=Children.toArray(children).filter(isValidElement).map(child=>{const p=child.props as {value?:string|number;children:ReactNode};return {value:String(p.value??p.children),label:p.children};});
 return <Select value={String(value)||"__all"} onValueChange={v=>onChange({target:{value:v==="__all"?"":String(v??"")}})}><SelectTrigger aria-label={label} className={"min-w-[150px] rounded-xl bg-white data-[size=default]:h-10 "+(className??"")}><SelectValue>{options.find(o=>o.value===String(value))?.label}</SelectValue></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value||"__all"}>{o.label}</SelectItem>)}</SelectContent></Select>;
}
const jobStatuses:Record<string,string>={DRAFT:"Bản nháp",PENDING:"Chờ duyệt",PUBLISHED:"Đang hiển thị",PAUSED:"Tạm dừng",REJECTED:"Bị từ chối",CLOSED:"Đã đóng",EXPIRED:"Hết hạn"};
type EmployerJob={id:string;title:string;status:string;deadlineAt:string|null;category:{name:string};province:{name:string};_count:{applications:number}};
export function EmployerJobs(){
 const account=useAccountStore(s=>s.account);
 const [page,setPage]=useState(1),[draft,setDraft]=useState(""),[query,setQuery]=useState(""),[status,setStatus]=useState("");
 const list=useQuery({queryKey:["employer",account?.id,"job-posts",page,query,status],enabled:account?.role==="company",queryFn:({signal})=>get<Page<EmployerJob>>("job-posts",{page,query,...(status?{status}:{})},signal)});
 return <Panel title="Tin tuyển dụng"><div className="mb-5 flex flex-wrap justify-between gap-3"><form className="flex flex-wrap gap-3" onSubmit={e=>{e.preventDefault();setQuery(draft);setPage(1);}}><input aria-label="Tìm theo tiêu đề" placeholder="Tìm theo tiêu đề" className={inputClass} value={draft} onChange={e=>setDraft(e.target.value)}/><EmployerDropdown aria-label="Trạng thái tin" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">Tất cả trạng thái</option>{Object.entries(jobStatuses).map(([k,v])=><option key={k} value={k}>{v}</option>)}</EmployerDropdown><button className={buttonClass}>Tìm kiếm</button></form><Link className={buttonClass} href="/employer/post-job">+ Đăng tin</Link></div>
 {list.isPending&&<p>Đang tải...</p>}{list.isError&&<ErrorRetry retry={()=>void list.refetch()}/>}
 {list.data&&<><p className="mb-3 text-sm text-slate-500">{list.data.total} tin tuyển dụng</p><div className="overflow-x-auto"><table className="w-full min-w-[600px] text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-3">Vị trí</th><th>Trạng thái</th><th>Ứng viên</th><th>Hạn nộp</th></tr></thead><tbody>{list.data.items.map(j=><tr key={j.id} className="border-b"><td className="p-3"><b>{j.title}</b><p className="text-xs text-slate-500">{j.category.name} · {j.province.name}</p></td><td>{jobStatuses[j.status]}</td><td>{j._count.applications}</td><td>{j.deadlineAt?new Date(j.deadlineAt).toLocaleDateString("vi-VN"):"Chưa có hạn"}</td></tr>)}</tbody></table>{!list.data.items.length&&<p className="p-8 text-center">Không tìm thấy tin tuyển dụng.</p>}</div><Pager page={page} pages={list.data.pages} change={setPage}/></>}</Panel>;
}
