import "dotenv/config";
import { test } from "node:test";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import express from "express";
import type { AddressInfo } from "node:net";
import adminRouter from "../routes/admin.route";
import employerRouter from "../routes/employer.route";
import { prisma } from "../utils/prisma";
import jwt from "../services/jwt.service";
import { redisClient } from "../utils/redis";
import { errorResponse } from "../utils/response";
import { AppError } from "../exceptions";

test("admin APIs isolate privileges, perform audited mutations and protect references",async()=>{
 const admin=await prisma.account.create({data:{email:`admin-test-${randomUUID()}@example.invalid`,role:"admin",passwordHash:"test"}});
 const user=await prisma.account.create({data:{email:`user-test-${randomUUID()}@example.invalid`,role:"candidate",passwordHash:"never-return-this"}});
 const company=await prisma.account.create({data:{email:`company-test-${randomUUID()}@example.invalid`,role:"company",passwordHash:"test",company:{create:{name:"Admin test",code:randomUUID()}}},include:{company:true}});
 const category=await prisma.jobCategory.create({data:{name:"Admin fixture",code:randomUUID()}});
 const ward=await prisma.ward.findFirstOrThrow();
 const job=await prisma.jobPost.create({data:{companyId:company.company!.id,title:"Admin fixture",address:"test",jobCategoryId:category.id,wardId:ward.id,provinceId:ward.provinceId,status:"PENDING",deadlineAt:new Date(Date.now()+86400000)}});
 const plan=await prisma.servicePlan.create({data:{name:"Admin test",code:randomUUID(),audience:"company",price:10000,durationDays:30}});
 const entitlement=await prisma.entitlement.findUniqueOrThrow({where:{code:"activeJobLimit"}});
 await prisma.planEntitlement.create({data:{planId:plan.id,entitlementId:entitlement.id,value:2}});
 const app=express();app.use(express.json());app.use("/admin/employer",employerRouter);app.use("/admin",adminRouter);app.use((error:unknown,_req:express.Request,res:express.Response,_next:express.NextFunction)=>errorResponse(res,error,error instanceof AppError?error.status:500));
 const server=app.listen(0);
 await new Promise<void>(resolve=>server.once("listening",resolve));
 const base=`http://127.0.0.1:${(server.address() as AddressInfo).port}/admin`;
 const token=jwt.createAccessToken(admin.id,"admin"),userToken=jwt.createAccessToken(user.id,"candidate");
 const request=async(path:string,method="GET",body?:unknown,auth=token)=>{
   const response=await fetch(base+path,{method,headers:{"Content-Type":"application/json",Authorization:"Bearer "+auth},...(body?{body:JSON.stringify(body)}:{})});
   return {status:response.status,body:await response.json()};
 };
 let extraCategory:string|null=null;
 try{
   const companyToken=jwt.createAccessToken(company.id,"company");
   const jobAction="/employer/job-posts/"+job.id+"/status";
   assert.equal((await request(jobAction,"PATCH",{status:"PUBLISHED"},companyToken)).status,409);
   await prisma.jobPost.update({where:{id:job.id},data:{status:"PUBLISHED"}});
   assert.equal((await request(jobAction,"PATCH",{status:"PAUSED"},companyToken)).status,200);
   assert.equal((await request(jobAction,"PATCH",{status:"PUBLISHED"},companyToken)).status,200);
   assert.equal((await request(jobAction,"PATCH",{status:"CLOSED"},companyToken)).status,200);
   assert.equal((await request(jobAction,"PATCH",{status:"PUBLISHED"},companyToken)).status,409);
   assert.equal((await request(jobAction,"PATCH",{status:"CLOSED"},userToken)).status,403);
   await prisma.jobPost.update({where:{id:job.id},data:{status:"PENDING"}});
   assert.equal((await request("/overview","GET",undefined,userToken)).status,403);
   for(const resource of ["overview","jobs","companies","accounts","plans","audit","notifications","categories","titles","provinces","wards","orders"])assert.equal((await request("/"+resource)).status,200,resource);
   const revenue=await request("/revenue?days=30");
   assert.equal(revenue.status,200);
   assert.equal(revenue.body.data.points.length,30);
   assert.equal(revenue.body.data.total,revenue.body.data.points.reduce((sum:number,p:{amount:number})=>sum+p.amount,0));
   assert.equal(revenue.body.data.total,revenue.body.data.candidate+revenue.body.data.company);
   assert.equal((await request("/revenue?days=365")).status,400);
   const monthly=await request("/revenue?mode=monthly&year=2026");
   assert.equal(monthly.status,200);
   assert.equal(monthly.body.data.points.length,12);
   assert.equal(monthly.body.data.points[0].day,"2026-01");
   assert.equal(monthly.body.data.points[11].day,"2026-12");
   assert.equal(monthly.body.data.total,monthly.body.data.points.reduce((s:number,p:{amount:number})=>s+p.amount,0));
   assert.equal((await request("/jobs?status=invalid")).status,400);
   const accounts=await request("/accounts?query="+encodeURIComponent(user.email));
   assert.equal(accounts.body.data.items[0].passwordHash,undefined);
   assert.equal((await request("/accounts/"+admin.id,"PATCH",{status:"blocked",reason:"Test protection"})).status,403);
   assert.equal((await request("/accounts/"+user.id,"PATCH",{status:"blocked",reason:"Test lock"})).status,200);
   assert.equal((await request("/overview","GET",undefined,userToken)).status,401);
   await request("/accounts/"+user.id,"PATCH",{status:"active",reason:"Test unlock"});
   assert.equal((await request("/jobs/"+job.id,"PATCH",{status:"PUBLISHED",reason:"Test approval"})).status,200);
   assert.equal((await prisma.jobPost.findUniqueOrThrow({where:{id:job.id}})).status,"PUBLISHED");
   const approved=await prisma.notification.findFirstOrThrow({where:{recipientAccountId:company.id,type:"job",title:"Tin tuyển dụng đã được duyệt"}});
   assert.equal(approved.link,"/employer?tab=jobs");
   assert.ok(approved.description.includes("Test approval"));
   assert.equal((await request("/jobs/"+job.id,"PATCH",{status:"PUBLISHED",reason:"Test duplicate"})).status,409);
   assert.equal(await prisma.notification.count({where:{recipientAccountId:company.id,type:"job"}}),1);
   assert.equal((await request("/jobs/"+job.id,"PATCH",{status:"PAUSED",reason:"Test pause"})).status,400);
   assert.equal((await request("/jobs/"+job.id,"PATCH",{status:"CLOSED",reason:"Test close"})).status,200);
   assert.equal((await prisma.jobPost.findUniqueOrThrow({where:{id:job.id}})).status,"CLOSED");
   assert.equal((await request("/jobs/"+job.id,"PATCH",{status:"CLOSED",reason:"Test duplicate close"})).status,409);
   await prisma.jobPost.update({where:{id:job.id},data:{status:"PAUSED"}});
   assert.equal((await request("/jobs/"+job.id,"PATCH",{status:"PUBLISHED",reason:"Test restore"})).status,409);
   assert.equal((await request("/jobs/"+job.id,"PATCH",{status:"CLOSED",reason:"Test paused close"})).status,200);
   assert.equal((await prisma.jobPost.findUniqueOrThrow({where:{id:job.id}})).status,"CLOSED");
   const closed=await prisma.notification.findFirstOrThrow({where:{recipientAccountId:company.id,title:"Tin tuyển dụng đã được đóng"}});
   assert.ok(closed.description.includes("Test close"));
   await prisma.jobPost.update({where:{id:job.id},data:{status:"PENDING"}});
   assert.equal((await request("/jobs/"+job.id,"PATCH",{status:"CLOSED",reason:"Test pending close"})).status,409);
   await prisma.jobPost.update({where:{id:job.id},data:{deadlineAt:new Date(Date.now()-1000)}});
   assert.equal((await request("/jobs/"+job.id,"PATCH",{status:"PUBLISHED",reason:"Test expired"})).status,409);
   assert.equal((await request("/companies/"+company.company!.id,"PATCH",{verificationStatus:"verified",reason:"Test verification"})).status,200);
   assert.equal(await prisma.notification.count({where:{recipientAccountId:company.id,type:"system"}}),1);
   await request("/companies/"+company.company!.id,"PATCH",{verificationStatus:"verified",reason:"Test retry"});
   assert.equal(await prisma.notification.count({where:{recipientAccountId:company.id,type:"system"}}),1);
   await request("/companies/"+company.company!.id,"PATCH",{verificationStatus:"rejected",reason:"Missing documents"});
   const rejected=await prisma.notification.findFirstOrThrow({where:{recipientAccountId:company.id,title:"Yêu cầu xác minh bị từ chối"}});
   assert.ok(rejected.description.includes("Missing documents"));
   assert.equal((await request("/catalog/categories/"+category.id,"DELETE")).status,409);
   const created=await request("/catalog/categories","POST",{name:"New fixture",code:"fixture-"+randomUUID()});
   assert.equal(created.status,200);
   extraCategory=(await prisma.jobCategory.findFirstOrThrow({where:{name:"New fixture",code:{startsWith:"fixture-"}}})).id;
   assert.equal((await request("/catalog/categories/"+extraCategory,"PATCH",{name:"Updated fixture",code:"updated-"+randomUUID()})).status,200);
   assert.equal((await request("/catalog/categories/"+extraCategory,"DELETE")).status,200);extraCategory=null;
   assert.equal((await request("/plans/"+plan.id,"PATCH",{price:20000,isActive:true,availability:"available",benefits:{activeJobLimit:3}})).status,200);
   assert.equal((await prisma.planEntitlement.findUniqueOrThrow({where:{planId_entitlementId:{planId:plan.id,entitlementId:entitlement.id}}})).value,3);
   const notification={email:user.email,title:"Test notification",description:"Fixture only",link:"/candidate",requestKey:randomUUID()};
   assert.equal((await request("/notifications","POST",notification)).status,200);
   assert.equal((await request("/notifications","POST",notification)).body.data.sent,0);
   assert.equal((await request("/notifications","POST",{...notification,link:"//example.invalid"})).status,400);
   assert.equal(await prisma.notification.count({where:{recipientAccountId:user.id,type:"system"}}),1);
   assert.ok(await prisma.auditLog.count({where:{actorAccountId:admin.id}})>=8);
 }finally{
   await new Promise<void>((resolve,reject)=>server.close(e=>e?reject(e):resolve()));
   await prisma.notification.deleteMany({where:{recipientAccountId:user.id}});
   await prisma.auditLog.deleteMany({where:{actorAccountId:admin.id}});
   await prisma.jobPost.delete({where:{id:job.id}});
   await prisma.company.delete({where:{id:company.company!.id}});
   await prisma.account.deleteMany({where:{id:{in:[admin.id,user.id,company.id]}}});
   await prisma.jobCategory.deleteMany({where:{id:{in:[category.id,...(extraCategory?[extraCategory]:[])]}}});
   await prisma.servicePlan.delete({where:{id:plan.id}});
   await prisma.$disconnect();await redisClient.quit();
 }
});
