// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/access-denied" | "/account/security" | "/admin" | "/billing/orders" | "/candidate" | "/career-guide" | "/career-guide/[slug]" | "/companies" | "/companies/[slug]" | "/cv-builder" | "/discover/[slug]" | "/employer" | "/employer/messages" | "/employer/post-job" | "/employer/services" | "/information/[slug]" | "/jobs/[id]" | "/login" | "/messages" | "/register" | "/services"
type AppRouteHandlerRoutes = "/api/auth" | "/api/auth/google" | "/api/auth/google/callback"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/access-denied": {}
  "/account/security": {}
  "/admin": {}
  "/api/auth": {}
  "/api/auth/google": {}
  "/api/auth/google/callback": {}
  "/billing/orders": {}
  "/candidate": {}
  "/career-guide": {}
  "/career-guide/[slug]": { "slug": string; }
  "/companies": {}
  "/companies/[slug]": { "slug": string; }
  "/cv-builder": {}
  "/discover/[slug]": { "slug": string; }
  "/employer": {}
  "/employer/messages": {}
  "/employer/post-job": {}
  "/employer/services": {}
  "/information/[slug]": { "slug": string; }
  "/jobs/[id]": { "id": string; }
  "/login": {}
  "/messages": {}
  "/register": {}
  "/services": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
