var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1ojgo0t._.js")
R.c("server/chunks/ssr/19xk_next_dist_20qi2jf._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0z3cori._.js")
R.c("server/chunks/ssr/[root-of-the-server]__04srves._.js")
R.c("server/chunks/ssr/frontend_src_0i6x9tl._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0oru0q0._.js")
R.c("server/chunks/ssr/frontend_158kqi-._.js")
R.c("server/chunks/ssr/19xk_next_dist_19jojun._.js")
R.c("server/chunks/ssr/frontend_090170_._.js")
R.c("server/chunks/ssr/19xk_next_dist_client_components_04ow902._.js")
R.c("server/chunks/ssr/19xk_next_dist_client_components_builtin_forbidden_0vfxd_t.js")
R.c("server/chunks/ssr/19xk_next_dist_client_components_builtin_unauthorized_098p3j3.js")
R.c("server/chunks/ssr/19xk_next_dist_client_components_builtin_global-error_0a0toiu.js")
R.c("server/chunks/ssr/frontend__next-internal_server_app_page_actions_0vnua0e.js")
R.m(27276)
module.exports=R.m(27276).exports
