import cvRouter from "./cv.route";
import adminRouter from "./admin.route";
import notificationRouter from "./notification.route";
import billingRouter from "./billing.route";
import applicationRouter from "./application.route";
import savedJobRouter from "./saved-job.route";
import employerRouter from "./employer.route";
import candidateRouter from "./candidate.route";
import express from "express";
import authRouter from "./auth.route";
import uploadRouter from "./upload.route";
import companyRouter from "./company.route";
import jobPostRouter from "./job-post.route";
import locationRouter from "./location.route";
import jobCategoryRouter from "./job-category.route";
import aiRouter from "./ai.route";
import conversationRouter from "./conversation.route";

const indexRouter = express.Router();
indexRouter.use("/admin", adminRouter);
indexRouter.use("/notifications", notificationRouter);
indexRouter.use("/billing", billingRouter);
indexRouter.use("/application", applicationRouter);
indexRouter.use("/saved-job", savedJobRouter);
indexRouter.use("/cv", cvRouter);
indexRouter.use("/auth", authRouter);
indexRouter.use("/upload", uploadRouter);
indexRouter.use("/company", companyRouter);
indexRouter.use("/job-post", jobPostRouter);
indexRouter.use("/location", locationRouter);
indexRouter.use("/job-category", jobCategoryRouter);
indexRouter.use("/candidate", candidateRouter);
indexRouter.use("/ai", aiRouter);
indexRouter.use("/conversation", conversationRouter);
indexRouter.use("/employer", employerRouter);
export default indexRouter;
