export const ERROR_CODE = {
  AUTH_SERVICE: {
    EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    ACCOUNT_BLOCKED: "ACCOUNT_BLOCKED",
    UNAUTHORIZED: "UNAUTHORIZED",
    ACCOUNT_NOT_FOUND: "ACCOUNT_NOT_FOUND",
    INVALID_TOKEN: "INVALID_TOKEN",
    OTP_INVALID: "OTP_INVALID"
  }
};